const express = require('express')
const cors = require('cors')
const profesionales = require('./Routes/profesionales')
const usuarios = require('./Routes/usuarios')
const servicios = require('./Routes/servicios.js')
const citas = require('./Routes/citas.js')
const horariosDisponibles = require('./Routes/horariosDisponibles.js')
const galeria = require('./Routes/galeria.js')
const reseñas = require('./Routes/reseñas.js')
const roles = require('./Routes/roles.js')
const app = express()

app.use(express.json())
app.use(cors())

app.use('/',profesionales)
app.use('/',usuarios)
app.use('/',servicios)
app.use('/',citas)
app.use('/',horariosDisponibles)
app.use('/',galeria)
app.use('/',reseñas)
app.use('/',roles)

app.listen(8000,()=> console.log('Escuchando en el puerto 8000'))